# Generated by Django 5.2.9 on 2025-12-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='energy_level',
            field=models.CharField(choices=[('high', 'High ⚡'), ('medium', 'Medium 🙂'), ('low', 'Low 😴')], default='medium', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moodentry',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='sleep_quality',
            field=models.CharField(choices=[('good', 'Good 😌'), ('average', 'Average 😐'), ('poor', 'Poor 😵')], default='average', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moodentry',
            name='stress_level',
            field=models.IntegerField(default=3, help_text='1 (Low) to 5 (High)'),
            preserve_default=False,
        ),
    ]
